[profile.default]
src = "contracts"      
test = "test"         
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.32"
optimizer = true
optimizer_runs = 200

libraries = [
    "poseidon-solidity/PoseidonT3.sol:PoseidonT3:0x317E17ba046F375FC5236cE2Eb76d1e69f9AD7d9",
    "@zk-kit/incremental-merkle-tree.sol/IncrementalBinaryTree.sol:IncrementalBinaryTree:0xF21AdA608A1a2a7AAa41aDfC8F8123Af22F3F42B"
]