[profile.default]
src = "contracts"      
test = "test"         
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.32"
optimizer = true
optimizer_runs = 200

libraries = [
    "poseidon-solidity/PoseidonT3.sol:PoseidonT3:0x01222BC962C6D7430f0e72D8A2c11a777F945B90",
    "@zk-kit/incremental-merkle-tree.sol/IncrementalBinaryTree.sol:IncrementalBinaryTree:0xBC4Eedc34B5F978F2f8D26B63cC77fCfa40Cc105"
]